//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchenkerFinlandOmbudAPIService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://myschenker.fi/ewebs/")]
    public partial class Authentication : object
    {
        
        private string accessKeyField;
        
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string accessKey
        {
            get
            {
                return this.accessKeyField;
            }
            set
            {
                this.accessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPoint", Namespace="http://myschenker.fi/ewebs/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchenkerFinlandOmbudAPIService.CollectionPointWithDistance))]
    public partial class CollectionPoint : object
    {
        
        private string Address1Field;
        
        private string Address2Field;
        
        private string BusinessHoursField;
        
        private string BusinessHours1Field;
        
        private string BusinessHours2Field;
        
        private string BusinessHours3Field;
        
        private string CityField;
        
        private string CollectionPointIDField;
        
        private string CollectionPointNameField;
        
        private string ContactPersonField;
        
        private string DistributionField;
        
        private string ExtraField;
        
        private string PhoneField;
        
        private string PostalCodeField;
        
        private int ProposalOrderField;
        
        private string TerminalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessHours
        {
            get
            {
                return this.BusinessHoursField;
            }
            set
            {
                this.BusinessHoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessHours1
        {
            get
            {
                return this.BusinessHours1Field;
            }
            set
            {
                this.BusinessHours1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessHours2
        {
            get
            {
                return this.BusinessHours2Field;
            }
            set
            {
                this.BusinessHours2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessHours3
        {
            get
            {
                return this.BusinessHours3Field;
            }
            set
            {
                this.BusinessHours3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionPointID
        {
            get
            {
                return this.CollectionPointIDField;
            }
            set
            {
                this.CollectionPointIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionPointName
        {
            get
            {
                return this.CollectionPointNameField;
            }
            set
            {
                this.CollectionPointNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson
        {
            get
            {
                return this.ContactPersonField;
            }
            set
            {
                this.ContactPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distribution
        {
            get
            {
                return this.DistributionField;
            }
            set
            {
                this.DistributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extra
        {
            get
            {
                return this.ExtraField;
            }
            set
            {
                this.ExtraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProposalOrder
        {
            get
            {
                return this.ProposalOrderField;
            }
            set
            {
                this.ProposalOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointWithDistance", Namespace="http://myschenker.fi/ewebs/")]
    public partial class CollectionPointWithDistance : SchenkerFinlandOmbudAPIService.CollectionPoint
    {
        
        private string DistanceField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointOrder", Namespace="http://myschenker.fi/ewebs/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchenkerFinlandOmbudAPIService.CollectionPointOrderWithBusinessID))]
    public partial class CollectionPointOrder : object
    {
        
        private SchenkerFinlandOmbudAPIService.Authentication AuthenticationField;
        
        private double CashOnDeliveryField;
        
        private string CollectionPointIDField;
        
        private string CustomerNumberField;
        
        private double PackageVolumeField;
        
        private double PackageWeightField;
        
        private string PickupAddressField;
        
        private string PickupAddress2Field;
        
        private string PickupCityField;
        
        private string PickupNameField;
        
        private string PickupPostalCodeField;
        
        private string ReceiverAddressField;
        
        private string ReceiverCityField;
        
        private string ReceiverContactField;
        
        private string ReceiverNameField;
        
        private string ReceiverPhoneField;
        
        private string ReceiverPostalCodeField;
        
        private string ReceiverReferenceField;
        
        private string SenderReferenceField;
        
        private string TradeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SchenkerFinlandOmbudAPIService.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CashOnDelivery
        {
            get
            {
                return this.CashOnDeliveryField;
            }
            set
            {
                this.CashOnDeliveryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CollectionPointID
        {
            get
            {
                return this.CollectionPointIDField;
            }
            set
            {
                this.CollectionPointIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PackageVolume
        {
            get
            {
                return this.PackageVolumeField;
            }
            set
            {
                this.PackageVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double PackageWeight
        {
            get
            {
                return this.PackageWeightField;
            }
            set
            {
                this.PackageWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupAddress
        {
            get
            {
                return this.PickupAddressField;
            }
            set
            {
                this.PickupAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupAddress2
        {
            get
            {
                return this.PickupAddress2Field;
            }
            set
            {
                this.PickupAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupCity
        {
            get
            {
                return this.PickupCityField;
            }
            set
            {
                this.PickupCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupName
        {
            get
            {
                return this.PickupNameField;
            }
            set
            {
                this.PickupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupPostalCode
        {
            get
            {
                return this.PickupPostalCodeField;
            }
            set
            {
                this.PickupPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverCity
        {
            get
            {
                return this.ReceiverCityField;
            }
            set
            {
                this.ReceiverCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverContact
        {
            get
            {
                return this.ReceiverContactField;
            }
            set
            {
                this.ReceiverContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverName
        {
            get
            {
                return this.ReceiverNameField;
            }
            set
            {
                this.ReceiverNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverPhone
        {
            get
            {
                return this.ReceiverPhoneField;
            }
            set
            {
                this.ReceiverPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverPostalCode
        {
            get
            {
                return this.ReceiverPostalCodeField;
            }
            set
            {
                this.ReceiverPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverReference
        {
            get
            {
                return this.ReceiverReferenceField;
            }
            set
            {
                this.ReceiverReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderReference
        {
            get
            {
                return this.SenderReferenceField;
            }
            set
            {
                this.SenderReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeName
        {
            get
            {
                return this.TradeNameField;
            }
            set
            {
                this.TradeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointOrderWithBusinessID", Namespace="http://myschenker.fi/ewebs/")]
    public partial class CollectionPointOrderWithBusinessID : SchenkerFinlandOmbudAPIService.CollectionPointOrder
    {
        
        private string SenderBusinessIDField;
        
        private string ReceiverBusinessIDField;
        
        private SchenkerFinlandOmbudAPIService.CPLabelType LabelSelectionField;
        
        private string ReceiverEmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderBusinessID
        {
            get
            {
                return this.SenderBusinessIDField;
            }
            set
            {
                this.SenderBusinessIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReceiverBusinessID
        {
            get
            {
                return this.ReceiverBusinessIDField;
            }
            set
            {
                this.ReceiverBusinessIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public SchenkerFinlandOmbudAPIService.CPLabelType LabelSelection
        {
            get
            {
                return this.LabelSelectionField;
            }
            set
            {
                this.LabelSelectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ReceiverEmail
        {
            get
            {
                return this.ReceiverEmailField;
            }
            set
            {
                this.ReceiverEmailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPLabelType", Namespace="http://schemas.datacontract.org/2004/07/eWebServiceDataContracts")]
    public enum CPLabelType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Long = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointReturn", Namespace="http://myschenker.fi/ewebs/")]
    public partial class CollectionPointReturn : object
    {
        
        private string ConsignmentNumberField;
        
        private string LabelURLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsignmentNumber
        {
            get
            {
                return this.ConsignmentNumberField;
            }
            set
            {
                this.ConsignmentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelURL
        {
            get
            {
                return this.LabelURLField;
            }
            set
            {
                this.LabelURLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelOrder", Namespace="http://myschenker.fi/ewebs/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchenkerFinlandOmbudAPIService.ParcelOrderWithBusinessID))]
    public partial class ParcelOrder : object
    {
        
        private SchenkerFinlandOmbudAPIService.Authentication AuthenticationField;
        
        private string CustomerNumberField;
        
        private System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.Address> AddressesField;
        
        private string SenderReferenceField;
        
        private string ReceiverReferenceField;
        
        private System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.GoodsLine> GoodslinesField;
        
        private double OrderTotalWeightField;
        
        private double OrderTotalVolumeField;
        
        private SchenkerFinlandOmbudAPIService.LabelType LabelSelectionField;
        
        private SchenkerFinlandOmbudAPIService.FreightPayer FreightPayerIsField;
        
        private string FreightPayerCustomerNumberField;
        
        private string TransporterInstructionsField;
        
        private string WaybillInstructionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SchenkerFinlandOmbudAPIService.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.Address> Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                this.AddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SenderReference
        {
            get
            {
                return this.SenderReferenceField;
            }
            set
            {
                this.SenderReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ReceiverReference
        {
            get
            {
                return this.ReceiverReferenceField;
            }
            set
            {
                this.ReceiverReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.GoodsLine> Goodslines
        {
            get
            {
                return this.GoodslinesField;
            }
            set
            {
                this.GoodslinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double OrderTotalWeight
        {
            get
            {
                return this.OrderTotalWeightField;
            }
            set
            {
                this.OrderTotalWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double OrderTotalVolume
        {
            get
            {
                return this.OrderTotalVolumeField;
            }
            set
            {
                this.OrderTotalVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public SchenkerFinlandOmbudAPIService.LabelType LabelSelection
        {
            get
            {
                return this.LabelSelectionField;
            }
            set
            {
                this.LabelSelectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public SchenkerFinlandOmbudAPIService.FreightPayer FreightPayerIs
        {
            get
            {
                return this.FreightPayerIsField;
            }
            set
            {
                this.FreightPayerIsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string FreightPayerCustomerNumber
        {
            get
            {
                return this.FreightPayerCustomerNumberField;
            }
            set
            {
                this.FreightPayerCustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string TransporterInstructions
        {
            get
            {
                return this.TransporterInstructionsField;
            }
            set
            {
                this.TransporterInstructionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string WaybillInstructions
        {
            get
            {
                return this.WaybillInstructionsField;
            }
            set
            {
                this.WaybillInstructionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelOrderWithBusinessID", Namespace="http://myschenker.fi/ewebs/")]
    public partial class ParcelOrderWithBusinessID : SchenkerFinlandOmbudAPIService.ParcelOrder
    {
        
        private string IsReceiverPrivatePersonField;
        
        private string SenderBusinessIDField;
        
        private string ReceiverBusinessIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IsReceiverPrivatePerson
        {
            get
            {
                return this.IsReceiverPrivatePersonField;
            }
            set
            {
                this.IsReceiverPrivatePersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderBusinessID
        {
            get
            {
                return this.SenderBusinessIDField;
            }
            set
            {
                this.SenderBusinessIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ReceiverBusinessID
        {
            get
            {
                return this.ReceiverBusinessIDField;
            }
            set
            {
                this.ReceiverBusinessIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://myschenker.fi/ewebs/")]
    public partial class Address : object
    {
        
        private SchenkerFinlandOmbudAPIService.AddressType AddressTypeField;
        
        private string ContactPersonField;
        
        private string ContactPhoneField;
        
        private string PartyNameField;
        
        private string AddressLineField;
        
        private string AdditionalAddresslineField;
        
        private string PostalCodeField;
        
        private string CityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SchenkerFinlandOmbudAPIService.AddressType AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson
        {
            get
            {
                return this.ContactPersonField;
            }
            set
            {
                this.ContactPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone
        {
            get
            {
                return this.ContactPhoneField;
            }
            set
            {
                this.ContactPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PartyName
        {
            get
            {
                return this.PartyNameField;
            }
            set
            {
                this.PartyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AddressLine
        {
            get
            {
                return this.AddressLineField;
            }
            set
            {
                this.AddressLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string AdditionalAddressline
        {
            get
            {
                return this.AdditionalAddresslineField;
            }
            set
            {
                this.AdditionalAddresslineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsLine", Namespace="http://myschenker.fi/ewebs/")]
    public partial class GoodsLine : object
    {
        
        private string MarksAndNumbersField;
        
        private string TradeNameField;
        
        private int PackageCountField;
        
        private SchenkerFinlandOmbudAPIService.PackageCode PackageCodeField;
        
        private double WeightField;
        
        private int LengthField;
        
        private int HeightField;
        
        private int WidthField;
        
        private double VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarksAndNumbers
        {
            get
            {
                return this.MarksAndNumbersField;
            }
            set
            {
                this.MarksAndNumbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TradeName
        {
            get
            {
                return this.TradeNameField;
            }
            set
            {
                this.TradeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PackageCount
        {
            get
            {
                return this.PackageCountField;
            }
            set
            {
                this.PackageCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public SchenkerFinlandOmbudAPIService.PackageCode PackageCode
        {
            get
            {
                return this.PackageCodeField;
            }
            set
            {
                this.PackageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelType", Namespace="http://schemas.datacontract.org/2004/07/eWebServiceDataContracts")]
    public enum LabelType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        A4 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        A5 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Long = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FreightPayer", Namespace="http://schemas.datacontract.org/2004/07/eWebServiceDataContracts")]
    public enum FreightPayer : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sender = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Receiver = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/eWebServiceDataContracts")]
    public enum AddressType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Receiver = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Departure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FreightPayer = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageCode", Namespace="http://schemas.datacontract.org/2004/07/eWebServiceDataContracts")]
    public enum PackageCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Package = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherPallet = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelOrderReturn", Namespace="http://myschenker.fi/ewebs/")]
    public partial class ParcelOrderReturn : object
    {
        
        private string CollectionDateField;
        
        private string ConsignmentNumberField;
        
        private string LabelURLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionDate
        {
            get
            {
                return this.CollectionDateField;
            }
            set
            {
                this.CollectionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsignmentNumber
        {
            get
            {
                return this.ConsignmentNumberField;
            }
            set
            {
                this.ConsignmentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelURL
        {
            get
            {
                return this.LabelURLField;
            }
            set
            {
                this.LabelURLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myschenker.fi/ewebs/", ConfigurationName="SchenkerFinlandOmbudAPIService.IWebService3_0")]
    public interface IWebService3_0
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointsByPostalCode", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointsByPostalCodeResponse" +
            "")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointsByPostalCodeResponse> getCollectionPointsByPostalCodeAsync(SchenkerFinlandOmbudAPIService.getCollectionPointsByPostalCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointsByCity", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointsByCityResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointsByCityResponse> getCollectionPointsByCityAsync(SchenkerFinlandOmbudAPIService.getCollectionPointsByCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointByID", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getCollectionPointByIDResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointByIDResponse> getCollectionPointByIDAsync(SchenkerFinlandOmbudAPIService.getCollectionPointByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/createOrder", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/createOrderResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.createOrderResponse> createOrderAsync(SchenkerFinlandOmbudAPIService.createOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/createOrderParcel", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/createOrderParcelResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.createOrderParcelResponse> createOrderParcelAsync(SchenkerFinlandOmbudAPIService.createOrderParcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getNearestCollectionPoints", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getNearestCollectionPointsResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getNearestCollectionPointsResponse> getNearestCollectionPointsAsync(SchenkerFinlandOmbudAPIService.getNearestCollectionPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getNearestCPWithDistance", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getNearestCPWithDistanceResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getNearestCPWithDistanceResponse> getNearestCPWithDistanceAsync(SchenkerFinlandOmbudAPIService.getNearestCPWithDistanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myschenker.fi/ewebs/IWebService3_0/getAllCollectionPoints", ReplyAction="http://myschenker.fi/ewebs/IWebService3_0/getAllCollectionPointsResponse")]
        System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getAllCollectionPointsResponse> getAllCollectionPointsAsync(SchenkerFinlandOmbudAPIService.getAllCollectionPointsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointsByPostalCode", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointsByPostalCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=1)]
        public string postalCode;
        
        public getCollectionPointsByPostalCodeRequest()
        {
        }
        
        public getCollectionPointsByPostalCodeRequest(SchenkerFinlandOmbudAPIService.Authentication auth, string postalCode)
        {
            this.auth = auth;
            this.postalCode = postalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointsByPostalCodeResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointsByPostalCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getCollectionPointsByPostalCodeResult;
        
        public getCollectionPointsByPostalCodeResponse()
        {
        }
        
        public getCollectionPointsByPostalCodeResponse(System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getCollectionPointsByPostalCodeResult)
        {
            this.getCollectionPointsByPostalCodeResult = getCollectionPointsByPostalCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointsByCity", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointsByCityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=1)]
        public string pCity;
        
        public getCollectionPointsByCityRequest()
        {
        }
        
        public getCollectionPointsByCityRequest(SchenkerFinlandOmbudAPIService.Authentication auth, string pCity)
        {
            this.auth = auth;
            this.pCity = pCity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointsByCityResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointsByCityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getCollectionPointsByCityResult;
        
        public getCollectionPointsByCityResponse()
        {
        }
        
        public getCollectionPointsByCityResponse(System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getCollectionPointsByCityResult)
        {
            this.getCollectionPointsByCityResult = getCollectionPointsByCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointByID", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=1)]
        public string cpID;
        
        public getCollectionPointByIDRequest()
        {
        }
        
        public getCollectionPointByIDRequest(SchenkerFinlandOmbudAPIService.Authentication auth, string cpID)
        {
            this.auth = auth;
            this.cpID = cpID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCollectionPointByIDResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getCollectionPointByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.CollectionPoint getCollectionPointByIDResult;
        
        public getCollectionPointByIDResponse()
        {
        }
        
        public getCollectionPointByIDResponse(SchenkerFinlandOmbudAPIService.CollectionPoint getCollectionPointByIDResult)
        {
            this.getCollectionPointByIDResult = getCollectionPointByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrder", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class createOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.CollectionPointOrderWithBusinessID order;
        
        public createOrderRequest()
        {
        }
        
        public createOrderRequest(SchenkerFinlandOmbudAPIService.CollectionPointOrderWithBusinessID order)
        {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrderResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class createOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.CollectionPointReturn createOrderResult;
        
        public createOrderResponse()
        {
        }
        
        public createOrderResponse(SchenkerFinlandOmbudAPIService.CollectionPointReturn createOrderResult)
        {
            this.createOrderResult = createOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrderParcel", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class createOrderParcelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.ParcelOrderWithBusinessID order;
        
        public createOrderParcelRequest()
        {
        }
        
        public createOrderParcelRequest(SchenkerFinlandOmbudAPIService.ParcelOrderWithBusinessID order)
        {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrderParcelResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class createOrderParcelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.ParcelOrderReturn createOrderParcelResult;
        
        public createOrderParcelResponse()
        {
        }
        
        public createOrderParcelResponse(SchenkerFinlandOmbudAPIService.ParcelOrderReturn createOrderParcelResult)
        {
            this.createOrderParcelResult = createOrderParcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNearestCollectionPoints", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getNearestCollectionPointsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=1)]
        public string searchAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=2)]
        public int amount;
        
        public getNearestCollectionPointsRequest()
        {
        }
        
        public getNearestCollectionPointsRequest(SchenkerFinlandOmbudAPIService.Authentication auth, string searchAddress, int amount)
        {
            this.auth = auth;
            this.searchAddress = searchAddress;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNearestCollectionPointsResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getNearestCollectionPointsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getNearestCollectionPointsResult;
        
        public getNearestCollectionPointsResponse()
        {
        }
        
        public getNearestCollectionPointsResponse(System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPoint> getNearestCollectionPointsResult)
        {
            this.getNearestCollectionPointsResult = getNearestCollectionPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNearestCPWithDistance", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getNearestCPWithDistanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=1)]
        public string searchAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=2)]
        public int amount;
        
        public getNearestCPWithDistanceRequest()
        {
        }
        
        public getNearestCPWithDistanceRequest(SchenkerFinlandOmbudAPIService.Authentication auth, string searchAddress, int amount)
        {
            this.auth = auth;
            this.searchAddress = searchAddress;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNearestCPWithDistanceResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getNearestCPWithDistanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPointWithDistance> getNearestCPWithDistanceResult;
        
        public getNearestCPWithDistanceResponse()
        {
        }
        
        public getNearestCPWithDistanceResponse(System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPointWithDistance> getNearestCPWithDistanceResult)
        {
            this.getNearestCPWithDistanceResult = getNearestCPWithDistanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCollectionPoints", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getAllCollectionPointsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public SchenkerFinlandOmbudAPIService.Authentication auth;
        
        public getAllCollectionPointsRequest()
        {
        }
        
        public getAllCollectionPointsRequest(SchenkerFinlandOmbudAPIService.Authentication auth)
        {
            this.auth = auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCollectionPointsResponse", WrapperNamespace="http://myschenker.fi/ewebs/", IsWrapped=true)]
    public partial class getAllCollectionPointsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myschenker.fi/ewebs/", Order=0)]
        public System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPointWithDistance> getAllCollectionPointsResult;
        
        public getAllCollectionPointsResponse()
        {
        }
        
        public getAllCollectionPointsResponse(System.Collections.Generic.List<SchenkerFinlandOmbudAPIService.CollectionPointWithDistance> getAllCollectionPointsResult)
        {
            this.getAllCollectionPointsResult = getAllCollectionPointsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IWebService3_0Channel : SchenkerFinlandOmbudAPIService.IWebService3_0, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebService3_0Client : System.ServiceModel.ClientBase<SchenkerFinlandOmbudAPIService.IWebService3_0>, SchenkerFinlandOmbudAPIService.IWebService3_0
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService3_0Client(EndpointConfiguration endpointConfiguration) : 
                base(WebService3_0Client.GetBindingForEndpoint(endpointConfiguration), WebService3_0Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3_0Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService3_0Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3_0Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService3_0Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointsByPostalCodeResponse> getCollectionPointsByPostalCodeAsync(SchenkerFinlandOmbudAPIService.getCollectionPointsByPostalCodeRequest request)
        {
            return base.Channel.getCollectionPointsByPostalCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointsByCityResponse> getCollectionPointsByCityAsync(SchenkerFinlandOmbudAPIService.getCollectionPointsByCityRequest request)
        {
            return base.Channel.getCollectionPointsByCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getCollectionPointByIDResponse> getCollectionPointByIDAsync(SchenkerFinlandOmbudAPIService.getCollectionPointByIDRequest request)
        {
            return base.Channel.getCollectionPointByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.createOrderResponse> createOrderAsync(SchenkerFinlandOmbudAPIService.createOrderRequest request)
        {
            return base.Channel.createOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.createOrderParcelResponse> createOrderParcelAsync(SchenkerFinlandOmbudAPIService.createOrderParcelRequest request)
        {
            return base.Channel.createOrderParcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getNearestCollectionPointsResponse> getNearestCollectionPointsAsync(SchenkerFinlandOmbudAPIService.getNearestCollectionPointsRequest request)
        {
            return base.Channel.getNearestCollectionPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getNearestCPWithDistanceResponse> getNearestCPWithDistanceAsync(SchenkerFinlandOmbudAPIService.getNearestCPWithDistanceRequest request)
        {
            return base.Channel.getNearestCPWithDistanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerFinlandOmbudAPIService.getAllCollectionPointsResponse> getAllCollectionPointsAsync(SchenkerFinlandOmbudAPIService.getAllCollectionPointsRequest request)
        {
            return base.Channel.getAllCollectionPointsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService3_0))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService3_01))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService3_0))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.myschenker.fi/ewebsecure3_0/WebService3_0.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService3_01))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.myschenker.fi/ewebsecure3_0/WebService3_0.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IWebService3_0,
            
            BasicHttpsBinding_IWebService3_01,
        }
    }
}
