//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchenkerOmbudAPIService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://privpakservices.schenker.nu/", ConfigurationName="SchenkerOmbudAPIService.packageservicesSoap")]
    public interface packageservicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/ConsignmentPrint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentPrintResponse> ConsignmentPrintAsync(SchenkerOmbudAPIService.ConsignmentPrintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/ConsignmentReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentReturnResponse> ConsignmentReturnAsync(SchenkerOmbudAPIService.ConsignmentReturnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/ConsignmentReturnPrint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentReturnPrintResponse> ConsignmentReturnPrintAsync(SchenkerOmbudAPIService.ConsignmentReturnPrintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/Return", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.ReturnResponse> ReturnAsync(SchenkerOmbudAPIService.ReturnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/NumberSeries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.NumberSeriesResponse> NumberSeriesAsync(SchenkerOmbudAPIService.NumberSeriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/SearchCollectionPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.SearchCollectionPointResponse> SearchCollectionPointAsync(SchenkerOmbudAPIService.SearchCollectionPointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/GetCollectionPointInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.GetCollectionPointInfoResponse> GetCollectionPointInfoAsync(SchenkerOmbudAPIService.GetCollectionPointInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://privpakservices.schenker.nu/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SchenkerOmbudAPIService.testResponse> testAsync(SchenkerOmbudAPIService.testRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class package
    {
        
        private string responseField;
        
        private string errormessageField;
        
        private string startnumField;
        
        private string stopnumField;
        
        private objLabelData labeldataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errormessage
        {
            get
            {
                return this.errormessageField;
            }
            set
            {
                this.errormessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string startnum
        {
            get
            {
                return this.startnumField;
            }
            set
            {
                this.startnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string stopnum
        {
            get
            {
                return this.stopnumField;
            }
            set
            {
                this.stopnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public objLabelData labeldata
        {
            get
            {
                return this.labeldataField;
            }
            set
            {
                this.labeldataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class objLabelData
    {
        
        private objConsignor consignorField;
        
        private objReturnTo returntoField;
        
        private objConsignee consigneeField;
        
        private objDeliverTo delivertoField;
        
        private string customerid_carrierField;
        
        private string printdateField;
        
        private string validtoField;
        
        private string productidField;
        
        private string productcodeField;
        
        private string producttextField;
        
        private string weightField;
        
        private string codField;
        
        private string cod_accountnumberField;
        
        private string consumeridField;
        
        private string referenceField;
        
        private string pp_referenceField;
        
        private string barcodeField;
        
        private string barcodetextField;
        
        private string printstreamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public objConsignor consignor
        {
            get
            {
                return this.consignorField;
            }
            set
            {
                this.consignorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public objReturnTo returnto
        {
            get
            {
                return this.returntoField;
            }
            set
            {
                this.returntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public objConsignee consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public objDeliverTo deliverto
        {
            get
            {
                return this.delivertoField;
            }
            set
            {
                this.delivertoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customerid_carrier
        {
            get
            {
                return this.customerid_carrierField;
            }
            set
            {
                this.customerid_carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string printdate
        {
            get
            {
                return this.printdateField;
            }
            set
            {
                this.printdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string validto
        {
            get
            {
                return this.validtoField;
            }
            set
            {
                this.validtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string productid
        {
            get
            {
                return this.productidField;
            }
            set
            {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string productcode
        {
            get
            {
                return this.productcodeField;
            }
            set
            {
                this.productcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string producttext
        {
            get
            {
                return this.producttextField;
            }
            set
            {
                this.producttextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cod
        {
            get
            {
                return this.codField;
            }
            set
            {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string cod_accountnumber
        {
            get
            {
                return this.cod_accountnumberField;
            }
            set
            {
                this.cod_accountnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string consumerid
        {
            get
            {
                return this.consumeridField;
            }
            set
            {
                this.consumeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string pp_reference
        {
            get
            {
                return this.pp_referenceField;
            }
            set
            {
                this.pp_referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string barcodetext
        {
            get
            {
                return this.barcodetextField;
            }
            set
            {
                this.barcodetextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string printstream
        {
            get
            {
                return this.printstreamField;
            }
            set
            {
                this.printstreamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class objConsignor
    {
        
        private string idField;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string postcodeField;
        
        private string localityField;
        
        private string countrycodeField;
        
        private string phonenumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string countrycode
        {
            get
            {
                return this.countrycodeField;
            }
            set
            {
                this.countrycodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string phonenumber
        {
            get
            {
                return this.phonenumberField;
            }
            set
            {
                this.phonenumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class CollectionPoint
    {
        
        private string cpointIDField;
        
        private string displayNameField;
        
        private string distanceField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string postCodeField;
        
        private string cityField;
        
        private string countryCodeField;
        
        private string openHoursField;
        
        private string openHours1Field;
        
        private string openHours2Field;
        
        private string openHours3Field;
        
        private string directionsField;
        
        private string cardAvailableField;
        
        private string cardNameField;
        
        private string cardInfoField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string consignmentProductIDField;
        
        private string returnProductIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CpointID
        {
            get
            {
                return this.cpointIDField;
            }
            set
            {
                this.cpointIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OpenHours
        {
            get
            {
                return this.openHoursField;
            }
            set
            {
                this.openHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OpenHours1
        {
            get
            {
                return this.openHours1Field;
            }
            set
            {
                this.openHours1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OpenHours2
        {
            get
            {
                return this.openHours2Field;
            }
            set
            {
                this.openHours2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OpenHours3
        {
            get
            {
                return this.openHours3Field;
            }
            set
            {
                this.openHours3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Directions
        {
            get
            {
                return this.directionsField;
            }
            set
            {
                this.directionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CardAvailable
        {
            get
            {
                return this.cardAvailableField;
            }
            set
            {
                this.cardAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CardName
        {
            get
            {
                return this.cardNameField;
            }
            set
            {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CardInfo
        {
            get
            {
                return this.cardInfoField;
            }
            set
            {
                this.cardInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ConsignmentProductID
        {
            get
            {
                return this.consignmentProductIDField;
            }
            set
            {
                this.consignmentProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReturnProductID
        {
            get
            {
                return this.returnProductIDField;
            }
            set
            {
                this.returnProductIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class objDeliverTo
    {
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string postcodeField;
        
        private string localityField;
        
        private string countrycodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string countrycode
        {
            get
            {
                return this.countrycodeField;
            }
            set
            {
                this.countrycodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class objConsignee
    {
        
        private string idField;
        
        private string nameField;
        
        private string attentionField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string postcodeField;
        
        private string localityField;
        
        private string countrycodeField;
        
        private string phonenumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string attention
        {
            get
            {
                return this.attentionField;
            }
            set
            {
                this.attentionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string countrycode
        {
            get
            {
                return this.countrycodeField;
            }
            set
            {
                this.countrycodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string phonenumber
        {
            get
            {
                return this.phonenumberField;
            }
            set
            {
                this.phonenumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://privpakservices.schenker.nu/")]
    public partial class objReturnTo
    {
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string postcodeField;
        
        private string localityField;
        
        private string countrycodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string countrycode
        {
            get
            {
                return this.countrycodeField;
            }
            set
            {
                this.countrycodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentPrint", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentPrintRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string printer;
        
        public ConsignmentPrintRequest()
        {
        }
        
        public ConsignmentPrintRequest(long customerID, string password, string barcode, string printer)
        {
            this.customerID = customerID;
            this.password = password;
            this.barcode = barcode;
            this.printer = printer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentPrintResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentPrintResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.package ConsignmentPrintResult;
        
        public ConsignmentPrintResponse()
        {
        }
        
        public ConsignmentPrintResponse(SchenkerOmbudAPIService.package ConsignmentPrintResult)
        {
            this.ConsignmentPrintResult = ConsignmentPrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentReturn", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentReturnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public string countrycode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=4)]
        public string consumername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=5)]
        public string consumeraddress1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=6)]
        public string consumeraddress2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=7)]
        public string consumerpostcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=8)]
        public string consumerlocality;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=9)]
        public string consumeremail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=10)]
        public string consumerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=11)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=12)]
        public string returnproductID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=13)]
        public string customername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=14)]
        public string printer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=15)]
        public string mode;
        
        public ConsignmentReturnRequest()
        {
        }
        
        public ConsignmentReturnRequest(
                    string countrycode, 
                    long customerID, 
                    string password, 
                    string barcode, 
                    string consumername, 
                    string consumeraddress1, 
                    string consumeraddress2, 
                    string consumerpostcode, 
                    string consumerlocality, 
                    string consumeremail, 
                    string consumerID, 
                    string reference, 
                    string returnproductID, 
                    string customername, 
                    string printer, 
                    string mode)
        {
            this.countrycode = countrycode;
            this.customerID = customerID;
            this.password = password;
            this.barcode = barcode;
            this.consumername = consumername;
            this.consumeraddress1 = consumeraddress1;
            this.consumeraddress2 = consumeraddress2;
            this.consumerpostcode = consumerpostcode;
            this.consumerlocality = consumerlocality;
            this.consumeremail = consumeremail;
            this.consumerID = consumerID;
            this.reference = reference;
            this.returnproductID = returnproductID;
            this.customername = customername;
            this.printer = printer;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentReturnResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentReturnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.package ConsignmentReturnResult;
        
        public ConsignmentReturnResponse()
        {
        }
        
        public ConsignmentReturnResponse(SchenkerOmbudAPIService.package ConsignmentReturnResult)
        {
            this.ConsignmentReturnResult = ConsignmentReturnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentReturnPrint", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentReturnPrintRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string barcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string printer;
        
        public ConsignmentReturnPrintRequest()
        {
        }
        
        public ConsignmentReturnPrintRequest(long customerID, string password, string barcode, string printer)
        {
            this.customerID = customerID;
            this.password = password;
            this.barcode = barcode;
            this.printer = printer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsignmentReturnPrintResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ConsignmentReturnPrintResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.package ConsignmentReturnPrintResult;
        
        public ConsignmentReturnPrintResponse()
        {
        }
        
        public ConsignmentReturnPrintResponse(SchenkerOmbudAPIService.package ConsignmentReturnPrintResult)
        {
            this.ConsignmentReturnPrintResult = ConsignmentReturnPrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ReturnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public string countrycode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string consumername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=4)]
        public string consumeraddress1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=5)]
        public string consumeraddress2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=6)]
        public string consumerpostcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=7)]
        public string consumerlocality;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=8)]
        public string consumeremail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=9)]
        public string consumerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=10)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=11)]
        public string returnproductID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=12)]
        public string customername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=13)]
        public string printer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=14)]
        public string mode;
        
        public ReturnRequest()
        {
        }
        
        public ReturnRequest(string countrycode, long customerID, string password, string consumername, string consumeraddress1, string consumeraddress2, string consumerpostcode, string consumerlocality, string consumeremail, string consumerID, string reference, string returnproductID, string customername, string printer, string mode)
        {
            this.countrycode = countrycode;
            this.customerID = customerID;
            this.password = password;
            this.consumername = consumername;
            this.consumeraddress1 = consumeraddress1;
            this.consumeraddress2 = consumeraddress2;
            this.consumerpostcode = consumerpostcode;
            this.consumerlocality = consumerlocality;
            this.consumeremail = consumeremail;
            this.consumerID = consumerID;
            this.reference = reference;
            this.returnproductID = returnproductID;
            this.customername = customername;
            this.printer = printer;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class ReturnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.package ReturnResult;
        
        public ReturnResponse()
        {
        }
        
        public ReturnResponse(SchenkerOmbudAPIService.package ReturnResult)
        {
            this.ReturnResult = ReturnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NumberSeries", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class NumberSeriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public string productID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public string countrycode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=4)]
        public int numoflabels;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=5)]
        public string customername;
        
        public NumberSeriesRequest()
        {
        }
        
        public NumberSeriesRequest(string productID, string countrycode, long customerID, string password, int numoflabels, string customername)
        {
            this.productID = productID;
            this.countrycode = countrycode;
            this.customerID = customerID;
            this.password = password;
            this.numoflabels = numoflabels;
            this.customername = customername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NumberSeriesResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class NumberSeriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.package NumberSeriesResult;
        
        public NumberSeriesResponse()
        {
        }
        
        public NumberSeriesResponse(SchenkerOmbudAPIService.package NumberSeriesResult)
        {
            this.NumberSeriesResult = NumberSeriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCollectionPoint", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class SearchCollectionPointRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string serviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public int paramID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=4)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=5)]
        public string postcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=6)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=7)]
        public int maxhits;
        
        public SearchCollectionPointRequest()
        {
        }
        
        public SearchCollectionPointRequest(long customerID, string key, string serviceID, int paramID, string address, string postcode, string city, int maxhits)
        {
            this.customerID = customerID;
            this.key = key;
            this.serviceID = serviceID;
            this.paramID = paramID;
            this.address = address;
            this.postcode = postcode;
            this.city = city;
            this.maxhits = maxhits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCollectionPointResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class SearchCollectionPointResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.CollectionPoint[] SearchCollectionPointResult;
        
        public SearchCollectionPointResponse()
        {
        }
        
        public SearchCollectionPointResponse(SchenkerOmbudAPIService.CollectionPoint[] SearchCollectionPointResult)
        {
            this.SearchCollectionPointResult = SearchCollectionPointResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCollectionPointInfo", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class GetCollectionPointInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public long customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=1)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=2)]
        public string serviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=3)]
        public string cpointID;
        
        public GetCollectionPointInfoRequest()
        {
        }
        
        public GetCollectionPointInfoRequest(long customerID, string key, string serviceID, string cpointID)
        {
            this.customerID = customerID;
            this.key = key;
            this.serviceID = serviceID;
            this.cpointID = cpointID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCollectionPointInfoResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class GetCollectionPointInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://privpakservices.schenker.nu/", Order=0)]
        public SchenkerOmbudAPIService.CollectionPoint[] GetCollectionPointInfoResult;
        
        public GetCollectionPointInfoResponse()
        {
        }
        
        public GetCollectionPointInfoResponse(SchenkerOmbudAPIService.CollectionPoint[] GetCollectionPointInfoResult)
        {
            this.GetCollectionPointInfoResult = GetCollectionPointInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class testRequest
    {
        
        public testRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://privpakservices.schenker.nu/", IsWrapped=true)]
    public partial class testResponse
    {
        
        public testResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface packageservicesSoapChannel : SchenkerOmbudAPIService.packageservicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class packageservicesSoapClient : System.ServiceModel.ClientBase<SchenkerOmbudAPIService.packageservicesSoap>, SchenkerOmbudAPIService.packageservicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public packageservicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(packageservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), packageservicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public packageservicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(packageservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public packageservicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(packageservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public packageservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentPrintResponse> ConsignmentPrintAsync(SchenkerOmbudAPIService.ConsignmentPrintRequest request)
        {
            return base.Channel.ConsignmentPrintAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentReturnResponse> ConsignmentReturnAsync(SchenkerOmbudAPIService.ConsignmentReturnRequest request)
        {
            return base.Channel.ConsignmentReturnAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.ConsignmentReturnPrintResponse> ConsignmentReturnPrintAsync(SchenkerOmbudAPIService.ConsignmentReturnPrintRequest request)
        {
            return base.Channel.ConsignmentReturnPrintAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.ReturnResponse> ReturnAsync(SchenkerOmbudAPIService.ReturnRequest request)
        {
            return base.Channel.ReturnAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.NumberSeriesResponse> NumberSeriesAsync(SchenkerOmbudAPIService.NumberSeriesRequest request)
        {
            return base.Channel.NumberSeriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.SearchCollectionPointResponse> SearchCollectionPointAsync(SchenkerOmbudAPIService.SearchCollectionPointRequest request)
        {
            return base.Channel.SearchCollectionPointAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.GetCollectionPointInfoResponse> GetCollectionPointInfoAsync(SchenkerOmbudAPIService.GetCollectionPointInfoRequest request)
        {
            return base.Channel.GetCollectionPointInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchenkerOmbudAPIService.testResponse> testAsync(SchenkerOmbudAPIService.testRequest request)
        {
            return base.Channel.testAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.packageservicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.packageservicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.packageservicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://privpakservices.schenker.nu/package/package_1.3/packageservices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.packageservicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://privpakservices.schenker.nu/package/package_1.3/packageservices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            packageservicesSoap,
            
            packageservicesSoap12,
        }
    }
}
