// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhipster.Internal.Api.Data.Data;

#nullable disable

namespace Zhipster.Internal.Api.Data.Migrations
{
    [DbContext(typeof(ZhipsterLocationDbContext))]
    [Migration("20230411110357_Initial DB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.BEZipCode", b =>
                {
                    b.Property<Guid>("BEZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BEZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BEZipCodeId");

                    b.ToTable("BEZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.DEZipCode", b =>
                {
                    b.Property<Guid>("DEZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DEZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DEZipCodeId");

                    b.ToTable("DEZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.DKZipCode", b =>
                {
                    b.Property<Guid>("DKZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DKZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DKZipCodeId");

                    b.ToTable("DKZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.FIZipCode", b =>
                {
                    b.Property<Guid>("FIZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FIZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FIZipCodeId");

                    b.ToTable("FIZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.FOZipCode", b =>
                {
                    b.Property<Guid>("FOZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FOZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FOZipCodeId");

                    b.ToTable("FOZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.ForwarderZipCodeSource", b =>
                {
                    b.Property<Guid>("ForwarderZipCodeSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ForwarderZipCodeSourceId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ForwarderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ForwarderId")
                        .HasColumnOrder(2);

                    b.Property<string>("ForwarderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ForwarderName")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ZipCodeSourceId")
                        .HasColumnOrder(3);

                    b.HasKey("ForwarderZipCodeSourceId");

                    b.ToTable("ForwarderZipCodeSources");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.GLZipCode", b =>
                {
                    b.Property<Guid>("GLZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GLZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GLZipCodeId");

                    b.ToTable("GLZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.ISZipCode", b =>
                {
                    b.Property<Guid>("ISZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ISZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ISZipCodeId");

                    b.ToTable("ISZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.NLZipCode", b =>
                {
                    b.Property<Guid>("NLZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NLZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NLZipCodeId");

                    b.ToTable("NLZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.NOZipCode", b =>
                {
                    b.Property<Guid>("NOZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NOZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NOZipCodeId");

                    b.ToTable("NOZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.SEZipCode", b =>
                {
                    b.Property<Guid>("SEZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SEZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SEZipCodeId");

                    b.ToTable("SEZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.SJZipCode", b =>
                {
                    b.Property<Guid>("SJZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SJZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(6);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(7);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SJZipCodeId");

                    b.ToTable("SJZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.USZipCode", b =>
                {
                    b.Property<Guid>("USZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USZipCodeId")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City")
                        .HasColumnOrder(3);

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("County")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsManuallyAddedZipCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTypeBox")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudeY")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LatitudeY")
                        .HasColumnOrder(7);

                    b.Property<string>("LongitudeX")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("LongitudeX")
                        .HasColumnOrder(8);

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Municipality")
                        .HasColumnOrder(4);

                    b.Property<string>("RoutingCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("StateCode")
                        .HasColumnOrder(6);

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ZipCodeSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("USZipCodeId");

                    b.ToTable("USZipCodes");
                });

            modelBuilder.Entity("Zhipster.Internal.Api.Data.Models.ZipCodeSource", b =>
                {
                    b.Property<Guid>("ZipCodeSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APILink")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SourceRecordCount")
                        .HasColumnType("int");

                    b.HasKey("ZipCodeSourceId");

                    b.ToTable("ZipCodeSources");
                });
#pragma warning restore 612, 618
        }
    }
}
